# Generate Only (Phase 1)
# Generates predictions and saves to disk, no metrics computed.
# Use this for large runs - if generation fails, you can resume.
# After completion, run with mode=evaluate to compute metrics.
#
# Usage:
#   python -m ragicamp.cli.run evaluation=generate ...
#   # Then later:
#   python -m ragicamp.cli.run evaluation=evaluate evaluation.predictions_path=outputs/.../predictions_raw.json

mode: generate
batch_size: 4
checkpoint_every: 10
resume_from_checkpoint: true
retry_failures: true
