# Quick Evaluation
# For testing and debugging
# ~1-2 minutes

mode: both
batch_size: 4
checkpoint_every: 5
resume_from_checkpoint: true
retry_failures: true

# Override dataset size for quick testing
# This is applied on top of dataset config
dataset_override:
  num_examples: 10
