# Baseline Study Evaluation (100 examples)
# Limited dataset for faster iteration during development
# Use evaluation=full for production runs

mode: both
batch_size: 4
checkpoint_every: 25
resume_from_checkpoint: true
retry_failures: true

# Override dataset size (100 questions)
# This will be applied via Hydra override
